version: '3.8'

services:
  frontend:
    image: ghcr.io/dimasinr/fe-quizjourney:v1
    container_name: frontend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`rapid.storyjourney.net`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt
      - traefik.http.routers.frontend.priority=1
      - traefik.http.services.frontend.loadbalancer.server.port=80
    healthcheck:
      # pilih salah satu: curl biasanya sudah ada di image Nginx/dotnet
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s

  backend:
    image: ghcr.io/dimasinr/be-quizjourney:v1
    container_name: backend
    restart: always
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5000
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    labels:
      - traefik.enable=true
      # Service backend (internal 5000)
      - traefik.http.services.backend.loadbalancer.server.port=5000

      # Router API
      - traefik.http.routers.backend_api.rule=Host(`rapid.storyjourney.net`) && PathPrefix(`/api`)
      - traefik.http.routers.backend_api.entrypoints=websecure
      - traefik.http.routers.backend_api.tls.certresolver=letsencrypt
      - traefik.http.routers.backend_api.service=backend
      - traefik.http.routers.backend_api.priority=100

      # Router SignalR (WebSocket)
      - traefik.http.routers.backend_hub.rule=Host(`rapid.storyjourney.net`) && (Path(`/roomHub`) || PathPrefix(`/roomHub/`))
      - traefik.http.routers.backend_hub.entrypoints=websecure
      - traefik.http.routers.backend_hub.tls.certresolver=letsencrypt
      - traefik.http.routers.backend_hub.service=backend
      - traefik.http.routers.backend_hub.priority=100

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
